import type { TourStepDef } from './types';

export const createGestorSteps = (t: (key: string) => string): TourStepDef[] => [
  {
    target: 'body',
    placement: 'center',
    title: t('gestor.welcome.title'),
    content: t('gestor.welcome.content'),
    skipBeacon: true,
  },
  {
    target: '[data-tour="forecast-cycle"]',
    placement: 'bottom',
    title: t('gestor.cycle.title'),
    content: t('gestor.cycle.content'),
    skipBeacon: true,
    data: { route: '/meu-forecast' },
  },
  {
    target: '[data-tour="forecast-kpi-bar"]',
    placement: 'bottom',
    title: t('gestor.kpiBar.title'),
    content: t('gestor.kpiBar.content'),
    skipBeacon: true,
    data: { route: '/meu-forecast' },
  },
  {
    target: '[data-tour="forecast-products"]',
    placement: 'top',
    title: t('gestor.products.title'),
    content: t('gestor.products.content'),
    skipBeacon: true,
    data: { route: '/meu-forecast' },
  },
  {
    target: '[data-tour="forecast-submit"]',
    placement: 'left',
    title: t('gestor.submit.title'),
    content: t('gestor.submit.content'),
    skipBeacon: true,
    data: { route: '/meu-forecast' },
  },
  {
    target: '[data-tour="consolidado-window"]',
    placement: 'bottom',
    title: t('gestor.consolidadoWindow.title'),
    content: t('gestor.consolidadoWindow.content'),
    skipBeacon: true,
    data: { route: '/consolidado' },
  },
  {
    target: '[data-tour="consolidado-kpis"]',
    placement: 'bottom',
    title: t('gestor.consolidadoKpis.title'),
    content: t('gestor.consolidadoKpis.content'),
    skipBeacon: true,
    data: { route: '/consolidado' },
  },
  {
    target: '[data-tour="consolidado-tabs"]',
    placement: 'top',
    title: t('gestor.consolidadoTabs.title'),
    content: t('gestor.consolidadoTabs.content'),
    skipBeacon: true,
    data: { route: '/consolidado' },
  },
  {
    target: '[data-tour="help-button"]',
    placement: 'bottom-end',
    title: t('gestor.help.title'),
    content: t('gestor.help.content'),
    skipBeacon: true,
    data: { route: '/consolidado' },
  },
];
