import type { TourStepDef } from './types';

export const createOperadorPcpSteps = (t: (key: string) => string): TourStepDef[] => [
  {
    target: 'body',
    placement: 'center',
    title: t('pcp.welcome.title'),
    content: t('pcp.welcome.content'),
    skipBeacon: true,
  },
  {
    target: '[data-tour="dashboard-kpis"]',
    placement: 'bottom',
    title: t('pcp.dashboardKpis.title'),
    content: t('pcp.dashboardKpis.content'),
    skipBeacon: true,
    data: { route: '/dashboard' },
  },
  {
    target: '[data-tour="aprovacoes-list"]',
    placement: 'top',
    title: t('pcp.aprovacoesList.title'),
    content: t('pcp.aprovacoesList.content'),
    skipBeacon: true,
    data: { route: '/aprovacoes' },
  },
  {
    target: '[data-tour="aprovacoes-filter"]',
    placement: 'bottom',
    title: t('pcp.aprovacoesFilter.title'),
    content: t('pcp.aprovacoesFilter.content'),
    skipBeacon: true,
    data: { route: '/aprovacoes' },
  },
  {
    target: '[data-tour="consolidado-window"]',
    placement: 'bottom',
    title: t('pcp.consolidadoWindow.title'),
    content: t('pcp.consolidadoWindow.content'),
    skipBeacon: true,
    data: { route: '/consolidado' },
  },
  {
    target: '[data-tour="consolidado-kpis"]',
    placement: 'bottom',
    title: t('pcp.consolidadoKpis.title'),
    content: t('pcp.consolidadoKpis.content'),
    skipBeacon: true,
    data: { route: '/consolidado' },
  },
  {
    target: '[data-tour="consolidado-chart"]',
    placement: 'top',
    title: t('pcp.consolidadoChart.title'),
    content: t('pcp.consolidadoChart.content'),
    skipBeacon: true,
    data: { route: '/consolidado' },
  },
  {
    target: '[data-tour="consolidado-tabs"]',
    placement: 'top',
    title: t('pcp.consolidadoTabs.title'),
    content: t('pcp.consolidadoTabs.content'),
    skipBeacon: true,
    data: { route: '/consolidado' },
  },
  {
    target: '[data-tour="help-button"]',
    placement: 'bottom-end',
    title: t('pcp.help.title'),
    content: t('pcp.help.content'),
    skipBeacon: true,
    data: { route: '/consolidado' },
  },
  {
    target: 'body',
    placement: 'center',
    title: t('pcp.done.title'),
    content: t('pcp.done.content'),
    skipBeacon: true,
    data: { route: '/consolidado' },
  },
];
